export const SITE={url:"https://companyflow.co.uk",title:"CompanyFlow UK | Web Design, Software, AI & Automation",description:"CompanyFlow UK delivers web design and development, custom software, CRM and ERP systems, AI automation, WhatsApp automation and e-commerce solutions for growing businesses."};
export const NAV=[["Solutions","#solutions"],["Industries","#industries"],["Products","#products"],["Work","#work"],["About","/about"]] as const;
export const SOLUTIONS=[
 ["Website & Digital Experience","High-performance websites designed to turn visitors into customers.","https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1400&q=85"],
 ["CRM & ERP","Business systems that bring customers, operations and data into one place.","https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85"],
 ["AI & Automation","Intelligent workflows that reduce repetitive work and respond faster.","https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85"],
 ["WhatsApp Automation","Turn conversations into customer journeys, support and sales workflows.","https://images.unsplash.com/photo-1614680376593-902f74cf0d41?auto=format&fit=crop&w=1400&q=85"],
 ["E-commerce","Modern online stores designed for conversion, retention and growth.","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=85"],
 ["Custom Software","Purpose-built technology for businesses with problems off the shelf software can't solve.","https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=85"]
] as const;
export const PRODUCTS=[
 ["AI & Customer Automation","AgentHub","AI-powered customer conversations, lead management and automation."],
 ["Travel Technology","Travel Platform","Modern technology for travel agencies, bookings and operations."],
 ["Business Software","Business ERP","Connected business management for teams that have outgrown spreadsheets."],
 ["Healthcare Technology","Laboratory Platform","Digital registration, reporting and communication workflows for laboratories."]] as const;
export const INDUSTRIES:Record<string,string>={Travel:"Bookings • Customers • Payments • Operations",Healthcare:"Registration • Reports • Communication • Records",Retail:"Store • Customers • Orders • Automation","Professional Services":"Clients • Projects • Invoicing • Follow-ups",Hospitality:"Reservations • Guests • Staff • Feedback","Local Businesses":"Website • Enquiries • Bookings • Reviews","E-commerce":"Catalogue • Checkout • Retention • Analytics",Other:"Tell us how your business works — we'll map the flow."};
export const INDUSTRY_IMAGES:Record<string,string>={
 Travel:"https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1600&q=85",
 Healthcare:"https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1600&q=85",
 Retail:"https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=85",
 "Professional Services":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85",
 Hospitality:"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=85",
 "Local Businesses":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=85",
 "E-commerce":"https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1600&q=85",
 Other:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=85"
};
export const STEPS=[["01","Discover","We understand your business, customers and workflow."],["02","Design","We design the experience, architecture and user journey."],["03","Build","We develop the website, software and integrations."],["04","Improve","We automate, optimise and continuously improve the system."]] as const;

export type Project = {
 slug:string; title:string; category:string; description:string; image:string;
 intro:string; challenge:string; solution:string; stats:[string,string][]; capabilities:string[];
};
export const WORK:Project[]=[
 {slug:"companyflow-website",title:"CompanyFlow Website",category:"Web Design & Digital Experience",description:"A conversion-focused digital experience for a UK technology partner covering websites, software, AI and automation.",image:"https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1000&q=88",intro:"A polished digital home for CompanyFlow, designed to explain complex technology services quickly and turn the right visitors into enquiries.",challenge:"The challenge was to present multiple services without making the business feel like a generic agency.",solution:"We built a structured experience around clear service groups, proof, industries and a focused enquiry journey.",stats:[["+38%","clearer service discovery"],["+42%","stronger CTA visibility"],["24/7","digital lead capture"]],capabilities:["Responsive UX","SEO foundations","Conversion journeys","Motion design"]},
 {slug:"destino-travels",title:"Destino Travels Platform",category:"Travel Technology",description:"A travel operations platform connecting search, bookings, customers, wallet payments and staff workflows.",image:"https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1000&q=88",intro:"A custom travel portal designed around the real operational flow of a modern travel agency.",challenge:"Travel teams need customers, bookings, payments, suppliers and internal operations connected without exposing sensitive supplier costs.",solution:"We designed separate customer, agent and admin workflows with booking, wallet, commission and operational layers.",stats:[["+45%","less manual coordination"],["+31%","faster booking workflow"],["1","connected operations hub"]],capabilities:["Next.js","Supabase","Booking workflows","Role-based portals"]},
 {slug:"agenthub",title:"AgentHub",category:"AI Customer Automation",description:"An AI sales and customer automation system built around WhatsApp conversations, lead handling and follow-ups.",image:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1000&q=88",intro:"AgentHub turns customer conversations into structured sales workflows while keeping people in control of high-value conversations.",challenge:"Businesses lose leads when enquiries arrive in chat but never become organised, qualified follow-ups.",solution:"We connected WhatsApp-first conversations with AI qualification, lead management, automation and human handover.",stats:[["+52%","faster first response"],["+36%","more structured follow-ups"],["24/7","automated availability"]],capabilities:["AI agents","WhatsApp automation","Lead qualification","Human handover"]},
 {slug:"labstacks",title:"LabStacks",category:"Healthcare Technology",description:"A multi-tenant diagnostic laboratory platform for registration, services, rates, reporting and communication workflows.",image:"https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=88",intro:"A business system built around the operational complexity of diagnostic laboratories and their different panels, services and rates.",challenge:"Laboratories need accurate service/rate control while keeping patient, panel and branch workflows organised.",solution:"We designed a multi-tenant workflow where panels control allowed services and rates, with room for reporting and communications.",stats:[["+40%","less repetitive data entry"],["+29%","faster service lookup"],["485+","service records supported"]],capabilities:["Multi-tenant architecture","Service/rate rules","Operational dashboards","Reporting workflows"]},
 {slug:"aurum-accessories",title:"Aurum Accessories",category:"E-commerce Experience",description:"A performance-focused commerce experience for an accessories brand, with conversion and mobile experience kept at the centre.",image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=88",intro:"An e-commerce experience where visual consistency and performance improvements have to work together without disrupting the live storefront.",challenge:"Improve mobile performance while protecting the existing customer-facing design and commerce behaviour.",solution:"We focused on the unpublished theme, image loading, script behaviour and rendering performance while preserving the live experience.",stats:[["+18%","faster key rendering"],["+24%","leaner critical delivery"],["100%","design-preservation focus"]],capabilities:["Shopify","Performance optimisation","Mobile UX","Theme-safe changes"]},
 {slug:"ai-sales-agent",title:"AI Sales Agent",category:"AI & Business Automation",description:"An AI sales workflow for finding prospects, structuring leads and automating the repetitive parts of outbound sales.",image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=88",intro:"A practical AI sales system designed to reduce repetitive prospecting work while keeping the sales process measurable and controllable.",challenge:"Manual prospecting consumes time before a salesperson ever reaches a qualified opportunity.",solution:"We structured the workflow around prospect discovery, enrichment, qualification and automated follow-up with clear handover points.",stats:[["+55%","prospecting time saved"],["+33%","faster lead qualification"],["1","repeatable sales workflow"]],capabilities:["Lead discovery","AI qualification","Automation","Sales dashboards"]}
];

export const NEEDS=["Website","CRM / ERP","AI","Automation","WhatsApp","E-commerce","Custom Software","Not sure yet"];
